# run
setting: 'tfbind8'

# wandb
wandb_mode: 'online'   # 'online', 'disabled'
wandb_project: 'led-gfn-tfbind'
wandb_entity: 'gflownet-silab'

# led gfn
led_step: 8
dropout: 0.1

# model learning
lr_z: 1.0e-2
lr_policy: 1.0e-4
lr_logF: 1.0e-4
clip_policy_logit_min: -50.0
clip_policy_logit_max: 50.0
clip_grad_norm: 10.0
clip_param: 0.2
entropy_coef: 0.01
sql_alpha: 0.01
model: 'subtb' # choices=['subtb', 'maxent', 'random', 'tb', 'db', 'subtb', 'db_fl', 'subtb_fl', 'db_rd', 'subtb_rd']
lamda: 0.99
init_logz: True
offline_select: 'prt'
sa_or_ssr: 'ssr'

# model architecture
ssr_encoder_hid_dim: 128
ssr_encoder_n_layers: 1
ssr_embed_dim: 128
ssr_scorer_hid_dim: 128
ssr_scorer_n_layers: 1
sa_hid_dim: 128
sa_n_layers: 2

# trainer
num_active_learning_rounds: 10000
num_samples_per_online_batch: 16
num_samples_per_offline_batch: 16

num_steps_per_batch: 3
num_online_batches_per_round: 1
num_offline_batches_per_round: 1
target_mix_backpolicy_weight: 0.25

# policy
explore_epsilon: 0.01

# guide
parallelize: True
num_guide_workers: 16

# experiment
replicate: 0
saved_models_dir: 'saved_models/tfbind8/'
save_every_x_active_rounds: 500

# monitor
monitor_num_samples: 128
monitor_fast_every: 10
monitor_slow_every: 200

# reward
scale_reward_min: 0.001
scale_reward_max: 1
reward_exp: 3

guide_sampling_temperature: 3.0

# experiment-specific
mdp_style: 'pa' # ['insert', 'pa']

# checkpointing
ckpt: -1
eval_num_samples: 128

# mcmc
mcmc: false
mh: false
k: 4

# checkpointing
ckpt: -1
eval_num_samples: 2048

# reproduction
seed: 0
